=== AshNinjaYT/Instituto/Achraf/Bloc2/Lenguaje de marcas/0373_ICA0_EAC1_Ben Tamou_Sbaihi/activitat_4.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">    
    <xs:element name="best_sellers">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="llibre" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nom" type="xs:string"/>
                            <xs:element name="editorial" type="xs:string"/>
                            <xs:element name="autor" type="xs:string"/>
                            <xs:element name="ISBN">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:length value="13"/>
                                        <xs:pattern value="\d{13}"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="protagonista" minOccurs="0" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="actor" type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="preu">
                                <xs:simpleType>
                                    <xs:restriction base="xs:decimal">
                                        <xs:minInclusive value="10"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="sinopsi" type="xs:string"/>
                        </xs:sequence>
                        <xs:attribute name="categoria" use="required">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:enumeration value="Ficció"/>
                                    <xs:enumeration value="No_Ficció"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                        <xs:attribute name="numero_pagines" type="xs:positiveInteger" use="optional"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== AshNinjaYT/Instituto/Achraf/S1/Lenguaje de marcas/0373_ICA0_EAC1_Ben Tamou_Sbaihi/activitat_4.xml
<?xml version="1.0" encoding="UTF-8"?>
<best_sellers xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="activitat_4.xsd">
    <llibre categoria="Ficció" numero_pagines="464">
        <nom>Història d'un piano</nom>
        <editorial>Columna</editorial>
        <autor>Ramón Gener</autor>
        <ISBN>9788466431682</ISBN>
        <protagonista>
            <actor>Janusz Borowski</actor>
        </protagonista>
        <preu>21.75</preu>
        <sinopsi>Història d’un piano és una novel·la captivadora sobre la força 
                d’un instrument que esdevé una metàfora del poder de redempció a través de l’amor, de l’amistat, 
                de la bellesa i, per descomptat, de la música</sinopsi>
    </llibre>
    <llibre categoria="Ficció" numero_pagines="448">
        <nom>Un animal salvatge</nom>
        <editorial>La Campana</editorial>
        <autor>Joël Dicker</autor>
        <ISBN>9788419245984</ISBN>
        <protagonista>
            <actor>Sophie Brown</actor>
        </protagonista>
        <preu>11.57</preu>
        <sinopsi>El 2 de juliol de 2022 dos delinqüents es disposen a dur a terme un atracament en una important joieria de Ginebra. 
        Un incident que difereix molt de ser un simple robatori. Vint dies abans, en una urbanització de luxe a la vora del llac Leman, 
        la Sophie Braun es prepara per celebrar el seu quarantè aniversari.</sinopsi>
    </llibre>

    <llibre categoria="Ficció" numero_pagines="160">
        <nom>Ocàs o fascinació</nom>
        <editorial>Club Editoria</editorial>
        <autor>Eva Baltasar</autor>
        <ISBN>9788473294294</ISBN>
        <protagonista>
            <actor></actor>
        </protagonista>
        <preu>17.57</preu>
        <sinopsi>Flotes, això és el màxim que has aconseguit. Tens mitja feina, 
        una habitació rellogada i un títol que acredita que ets dels que no poden caure. 
        Però caus. El risc ha entrat a la teva vida sense que el veiessis venir</sinopsi>
    </llibre>

    <llibre categoria="No_Ficció" numero_pagines="256">
        <nom>Aprendre a esquivar les bales</nom>
        <editorial>La Campana</editorial>
        <autor>Xavi Coral</autor>
        <ISBN>9788419245434</ISBN>
        <protagonista>
            <actor></actor>
        </protagonista>
        <preu>20.80</preu>
        <sinopsi>Amb l'inici de la Guerra Civil, 
        Josep Trullàs decideix allistar-se voluntari a defensar la República, 
        deixant a Terrassa la família i un futur prometedor</sinopsi>
    </llibre>

</best_sellers>
